import os

# global vars

MIN_WIDTH = 1200
MIN_HEIGHT = 1000
APP_TITLE = 'NEXACut Pro'

CURRENT_DIR = os.path.dirname(__file__)

# frontend

FRONTEND_FOLDER = 'frontend'
FRONTEND_FOLDER_PATH = os.path.join(CURRENT_DIR, FRONTEND_FOLDER)

RESOURCES_FOLDER = 'resources'
RESOURCES_FOLDER_PATH = os.path.join(FRONTEND_FOLDER_PATH, RESOURCES_FOLDER)

FONT_FOLDER = 'fonts'
FONT_FOLDER_PATH = os.path.join(RESOURCES_FOLDER_PATH, FONT_FOLDER)

MAIN_FONT = 'Tajawal-Regular.tff'
MAIN_FONT_PATH = os.path.join(FONT_FOLDER_PATH, MAIN_FONT)

IMAGES_FOLDER = 'images'
IMAGES_PATH = os.path.join(RESOURCES_FOLDER_PATH, IMAGES_FOLDER)

LOGO_IMAGE = 'NEXACut Logo.png'
LOGO_PATH = os.path.join(IMAGES_PATH, LOGO_IMAGE)

STYLESHEET_FOLDER = 'stylesheets'
STYLESHEET_FOLDER_PATH = os.path.join(RESOURCES_FOLDER_PATH, STYLESHEET_FOLDER)

# data

DATA_FOLDER = 'data'
DATA_FOLDER_PATH = os.path.join(CURRENT_DIR, DATA_FOLDER)

CAD_PREVIEW_DATA_FOLDER = 'cad_preview_data'
CAD_PREVIEW_DATA_PATH = os.path.join(DATA_FOLDER_PATH, CAD_PREVIEW_DATA_FOLDER)

IMAGE_PREVIEW_DATA_FOLDER = 'image_preview_data'
IMAGE_PREVIEW_DATA_PATH = os.path.join(DATA_FOLDER_PATH, IMAGE_PREVIEW_DATA_FOLDER)

ROUTER_PREVIEW_DATA_FOLDER = 'router_preview_data'
ROUTER_PREVIEW_DATA_PATH = os.path.join(DATA_FOLDER_PATH, ROUTER_PREVIEW_DATA_FOLDER)

PLATE_DATA_FOLDER = 'plate_data'
PLATE_DATA_FOLDER_PATH =  os.path.join(DATA_FOLDER_PATH, PLATE_DATA_FOLDER)

PLATE_DATA_PREVIEW_FOLDER = 'plate_preview_data'
PLATE_DATA_PREVIEW_FOLDER_PATH = os.path.join(DATA_FOLDER_PATH, PLATE_DATA_PREVIEW_FOLDER)

ROUTER_DATA_FOLDER = 'router_data'
ROUTER_DATA_FOLDER_PATH = os.path.join(DATA_FOLDER_PATH, ROUTER_DATA_FOLDER)

PREFERENCE_DATA_FOLDER = 'preference_data'
PREFERENCE_DATA_FOLDER_PATH = os.path.join(CURRENT_DIR, DATA_FOLDER, PREFERENCE_DATA_FOLDER)

USER_PREFERENCE_FILE = 'user_preferences.json'
USER_PREFERENCE_FILE_PATH = os.path.join(PREFERENCE_DATA_FOLDER_PATH, USER_PREFERENCE_FILE)

DEFAULT_PREFERENCE_FILE = 'default_preferences.json'
DEFAULT_PREFERENCE_FILE_PATH = os.path.join(PREFERENCE_DATA_FOLDER_PATH, DEFAULT_PREFERENCE_FILE)
